### ISSUE TITLE
Error: SMTP AUTH extension not supported by server - Fixed

### ISSUE THREAD

**Issue by kaizimm99** [mkhaled87/DormantBitcoinHunter#1]
### Issue:
To be sure that emails are sent correctly, I tried the _send_email_ method seperatly. 

Turns out there will be an error when sending a mail:
**smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server**

### Steps to fix:
1.) import ssl
```
import ssl
```

2.) add a _context_ variable to _send_email_ method and call _smtplib_. Final method looks like this (the two added lines are marked):

```
def send_email(lucky_text):
        text = env.email_text + "\n" + lucky_text
        msg = EmailMessage()
        msg.set_content(text)
        msg['Subject'] = env.subject
        msg['From'] = env.SEND_FROM
        msg['To'] = env.SEND_TO
        context=ssl.create_default_context()                                #line added
        s = smtplib.SMTP(env.SMTP_HOST, env.SMTP_PORT)
        s.starttls(context=context)                                         #line added
        s.login(env.USER, env.PASS)
        s.send_message(msg)
        s.quit()
        print('Lucky Email sent!')
```

Note: This works fine when using a **gmail** account to send mails with **smtp.gmail.com host on port 587**.
Used system: Windows

Source: https://stackoverflow.com/a/58997830

**Comment by mkhaled87** [comment]
Thanks @kaizimm99, TBH, when i tested it I used a local SMTP server! I'll add your mods.
