### ISSUE TITLE
How is duplication of work handled?

### ISSUE THREAD

**Issue by rohitghali** [mkhaled87/DormantBitcoinHunter#3]
Pardon me for my as this might seem a simple doubt. I'm a beginner. But, once I stop and start the instance again, does it not generate same addresses as previous session again? I know it is random with RNG. But, still, isn't there a chance of creating same addresses as before? Isn't there a chance of duplication of efforts between sessions? What are the odds of that happening and how is it handled?

**Comment by mkhaled87** [comment]
Hi, I am using `os.urandom` to generate the random private keys. With that extremely large size of search space, it is highly unlikely that the same key will be generated again.
