### ISSUE TITLE
i have no idea why this dosent work

### ISSUE THREAD

**Issue by lowker21** [mkhaled87/DormantBitcoinHunter#5]
everytime i try to run hunt.py it dosent work and when i try to run python hunt.,py it tells me 
"python: can't open file 'C:\\WINDOWS\\system32\\hunt.py': [Errno 2] No such file or directory"

**Comment by mkhaled87** [comment]
It looks like this is an incorrect-path issue. "'C:\WINDOWS\system32\hunt.py" does not look like the correct path for the file:  may be  python is looking for the hunt.py in system32 because you supplied the path incorrectly. Try "python .\hunt.py"

**Comment by lowker21** [comment]
nope same thing happened, "python: can't open file 'C:\\WINDOWS\\system32\\hunt.py': [Errno 2] No such file or directory"

**Comment by lowker21** [comment]
im not sure but i think i fixed it? also does the hunt.py take this long to load?

**Comment by lowker21** [comment]
also can you use the cd command to use the hunt.py in the dormantbitcoin file?

**Comment by lowker21** [comment]
do you have like an example that i can see what it looks like when you run it correctly?

**Comment by lowker21** [comment]
sorry for asking so many question i really new to this.

**Comment by mkhaled87** [comment]
This should run forever and will only show positive output when a hit happens (unlikely). Remember: this project is developed for fun. There is an almost-zero probability you can find the private key of a given BTC address using your normal computer (or even many average-computing-power machines).
