### ISSUE TITLE
Does it pick up where it left off after you stop the process?

### ISSUE THREAD

**Issue by lifeandtimes89** [mkhaled87/DormantBitcoinHunter#6]
Hey,

Currently have your code running, fun project, I was wondering though when you stop the process does it pick up where the last process stopped or does it start fresh again? How do you ensure theres no duplicates?

Also is there anyway to send a test email to ensure that if it does find something you do get the email? Or does the key txt file auto update just to check?

Thanks :-)

**Comment by mkhaled87** [comment]
Nope, it doesn't start from where it has stopped and there is no guarantee there will not be duplicates. The search space is very large though, and duplicates are very rare.

Yeo it can be changed to send a test email, for example sending an email in the beginning of the search. Feel free to update it and create a PR.
